### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by geovey** [dabamos/openadms-ui#1]
Access to XMLHttpRequest at 'http://127.0.0.1:443/api/v1/' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by interkosmos** [comment]
By default, the OpenADMS Server configuration file for nginx [enables CORS headers](https://github.com/dabamos/openadms-server/blob/28ba844acb58b7dd8dd94a5fb91bf5649a590627/nginx/nginx.conf#L81).
